### ISSUE TITLE
as.network data error_Error x contains loops

### ISSUE THREAD

**Issue by njatel** [statnet/network#67] opened 2021-09-19 14:51 UTC
> net_69 <- as.network(data_69, bipartite=T, directed=F, loops = F)
Error: `loops` is `FALSE`, but `x` contains loops.
The following values are affected:
	- `x[2, 1:2]`
	- `x[3, 1:2]`
	- `x[5, 1:2]`
	- `x[7, 1:2]`
	- `x[12, 1:2]`
	- `x[13, 1:2]`

> data_69
   X1969.01.22 X1969.02.11 X1969.05.01 X1969.06.05 X1969.07.03 X1969.08.14 X1969.09.06 X1969.10.09 X1969.11.13
1            1           0           1           0           1           0           0           0           0
2            1           1           1           0           1           1           1           1           1
3            1           1           1           1           1           1           1           1           1
5            0           1           0           0           0           0           0           0           0
6            0           0           1           1           0           0           0           1           0

**Comment by CarterButts** [comment] 2021-09-20 00:42
This is a duplicate of an issue I created earlier today - see that one.  (The issue is that `as.network.data.frame` does not obey standard semantics.  The workaround is to either wrap the data object in `as.matrix` or explicitly call `as.network.matrix`.)

**Closed by CarterButts** 2021-09-20 00:42 UTC
