### ISSUE TITLE
How to release the memory held by a `network` object

### ISSUE THREAD

**Issue by AdrienLeGuillou** [statnet/network#80] opened 2022-07-26 15:58 UTC
Hi, 

I noticed that removing a `network` object with `rm(nw); gc()` does not release the memory. I encountered this when we tried to split `EpiModel::netsim` parallel code into 2 calls of `foreach`. The first for model initialization and the second for the time loop. 
When doing so, the memory used by the simulation was twice as much as before.

I tried to make a simple example that I could monitor from `htop` to see the actual residential memory used at each step. The `Sys.sleep(30)` are to allow me the time to record the results.

```r
library(EpiModel)
library(future.apply)
plan(multicore, workers = 4) 

n <- 1e5
print("Before Future 1")
Sys.sleep(30)
print("Future 1")
nws <- future.apply::future_lapply(1:4, function(x) {
  nw <- network.initialize(n, directed = FALSE, hyper = FALSE, loops = FALSE,
                           multiple = FALSE, bipartite = FALSE)
  nw <- set.vertex.attribute(nw, "race", rbinom(n, 1, 0.5), n)
  Sys.sleep(30)
  nw
}, future.seed = TRUE)

print("Future 2")

nws <- future.apply::future_lapply(nws, function(nw) {
  nw <- set.vertex.attribute(nw, "smth", rbinom(n, 1, 0.5), n)
  Sys.sleep(30)
  nw
}, future.seed = TRUE)

print("End Future 2")
Sys.sleep(30)

print("GC:")
rm(nws); gc()
Sys.sleep(30)
```

I noticed 2 problem, the first is that when the second `future_lapply` starts, the memory used by each worker is twice as much as if both  `set.vertex.attribute` calls were in the same `future_lapply` function. The second is that `rm(nws); gc()` does not release any memory.

This is actually not really an issue with EpiModel as our simulations now only have one call of `foreach` that create workers and we usually stop the whole R process after the simulation is saved. But maybe that's something you might want to know.

Note: Using the `multisession` plan (for Rstudio and Windows) give different result that still indicate that the memory is not released when their jobs are done.

**Comment by smjenness** [comment] 2022-07-26 16:06
cc: @martinamorris, @chad-klumb, @krivit

**Comment by CarterButts** [comment] 2022-07-26 17:05
Hmm.  All memory allocation in the current network backend is performed using standard R allocators, and is subject to the usual garbage collection rules (which are governed by R, and not by `network`).  (I have spent a lot of quality time with `Rchk`, ensuring that the protection stack is rightly defended from threats real and hypothetical.)  However, IIRC R does not guarantee that memory deallocated in this way is immediately released from the R process.  It is thus possible (AFAIK) that one could `rm()` a network object and force garbage collection, only to find that one's R process is not correspondingly diminished.  However, if that is so, you should (again AFAIK) find that when you allocate other objects, the reserved memory gets used for them.  That's an R thing, and not a network thing - part of the price of handing over control of memory to the garbage collection system is that one loses the power to determine when the trash is taken out, much less where it gets dumped. 

With respect to your specific example, I see that you are using R's parallel architecture.  That infrastructure does a lot of bloated things with memory (including making a lot of copies of a lot of objects across processes), and it may be making its own decisions about what it will recycle and when.  So, if one is concerned about memory issues with `statnet` components *per se,* one should not try to examine them in a parallel context - what can seem like a deallocation problem is actually a side effect of how the parallel processing infrastructure handles its affairs.

(In that vein, it _is_ possible to avoid the memory bloat, but AFAIK only by using OMP or the like.  In that case, one can share objects across processes without copying, but one *cannot* use any R memory allocators, nor indeed anything else in the R library.  So one is then back to vanilla C memory management, with its associated pros and cons.  `parallel` and friends give one the convenience of not having to do low-level code re-engineering, but they extract a heavy price in terms of footprint.  If one wants really efficient parallelization, the only way to achieve it is to manage things oneself.) 

Anyway, if we find that R is persistently refusing to deallocate memory from removed network objects in the base (non-parallel) environment, and that this is above and beyond R's usual behavior, then this would seem to bear examining further.  I've not seen evidence of that but life is long.  I'm skeptical, because the way we handle memory is very standard, and network objects should look no different to the garbage collector than anything else in R....but hidden gotchas are not unknown. 

I'm going to close this, as it seems not to be a bug, but if one is found then it can be reopened.

**Closed** 2022-07-26 17:05 UTC

**Comment by AdrienLeGuillou** [comment] 2022-07-27 14:59
Thank you so much for your explanation, I am definitively not an expert on memory allocation in R when working with the lower level API. And again, for our work this is a non issue due to the way we interact with statnet packages.

For reference, below is the single thread example I was playing with as well at the time where I create big networks and big runif vectors and monitor how memory is allocated on the process. The values in comment are first the output of `pryr::mem_used()` then the RES memory of the process by `htop` and finally the total memory used by my OS during the course of the script. 

```r
library(network)
library(pryr)

n <- 1e6
print("Before NW")
print(mem_used())
# 52MB; residential memory: 113MB; memory used overall 775MB

Sys.sleep(30)
print("Allocate runif")
x <- runif(100 * n)
print("runif allocated")
print(mem_used())
# 852MB; residential memory:877MB; memory used overall 1510MB

Sys.sleep(30)
print("rm runif and GC")
rm(x)
gc(full = TRUE)
print(mem_used())
# 52MB; residential memory:114MB; memory used overall 789MB

Sys.sleep(30)
print("Allocate NW")
nw <- network.initialize(n, directed = FALSE, hyper = FALSE, loops = FALSE, multiple = FALSE, bipartite = FALSE)
print("NW allocated")
print(mem_used())
# 516MB; residential memory:934MB; memory used overall 1560MB


Sys.sleep(30)
print("rm NW and GC")
rm(nw)
gc(full = TRUE)
print(mem_used())
# 52MB; residential memory:926MB; memory used overall 1550MB

Sys.sleep(30)
print("Allocate runif")
y <- runif(100 * n)
print("runif allocated")
print(mem_used())
# 852MB; residential memory:1689MB; memory used overall 2290MB

Sys.sleep(30)
print("rm runif and GC")
rm(y)
gc(full = TRUE)
print(mem_used())
# 52MB; residential memory:926MB; memory used overall 1550MB

Sys.sleep(30)
print("Allocate NW")
nw2 <- network.initialize(n, directed = FALSE, hyper = FALSE, loops = FALSE, multiple = FALSE, bipartite = FALSE)
print("NW allocated")
print(mem_used())
# 516MB; residential memory:965MB; memory used overall 1590MB

Sys.sleep(30)
print("rm NW and GC")
rm(nw2)
gc(full = TRUE)
print(mem_used())
# 52MB; residential memory:934MB; memory used overall 1550MB
```

**Comment by CarterButts** [comment] 2022-07-27 16:59
Hi, Adrien.  That's interesting - it looks like R is indeed freeing the allocated memory internally, but not always letting go of it to the OS.  I note in your example that the self-reported memory allocation goes down after `rm()` as it should, and when the R process doesn't let go of the memory (per your second number) it seems to reuse it. 
 Here's a corresponding case using R's self-reporting on my system:

```
 > gc()
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 271460 14.5     666585 35.6   410182 22.0
Vcells 543296  4.2    8388608 64.0  1821062 13.9
> library(network)

‘network’ 1.17.2 (2022-05-20), part of the Statnet Project
* ‘news(package="network")’ for changes since last version
* ‘citation("network")’ for citation information
* ‘https://statnet.org’ for help, support, and other information

> gc()
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 502996 26.9    1103838   59   666585 35.6
Vcells 938875  7.2    8388608   64  1821062 13.9
> net<-network.initialize(10000)
> gc()
          used (Mb) gc trigger (Mb) max used (Mb)
Ncells  574668 30.7    1103838   59   667341 35.7
Vcells 1032139  7.9    8388608   64  1821062 13.9
> rm(net)
> gc()
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 504649 27.0    1103838   59   667341 35.7
Vcells 942099  7.2    8388608   64  1821062 13.9
> net<-network.initialize(1e6)
> gc()
          used  (Mb) gc trigger   (Mb) max used  (Mb)
Ncells 7504669 400.8   22087225 1179.6 15505669 828.1
Vcells 9942139  75.9   22044408  168.2 18942417 144.6
> rm(net)
> gc()
         used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 504649 27.0   17669780 943.7 15505669 828.1
Vcells 942099  7.2   17635527 134.6 18942417 144.6
> net<-network.initialize(1e6,directed=F)
> gc()
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 7504670 400.8   17669780 943.7 15505669 828.1
Vcells 9942139  75.9   17635527 134.6 18942417 144.6
> rm(net)
> gc()
         used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 504650 27.0   14135824 755.0 15505669 828.1
Vcells 942099  7.2   14108422 107.7 18942417 144.6
```

So, the garbage collector appears to be reporting the intended behavior, as it is in your case.  Running `htop` gives me similar results to yours, though, so it is clear that the master R process doesn't always surrender memory to the OS after taking out the trash.

Plausibly, R is caching some of that deallocated memory, on the theory that if you've been allocating a lot of stuff, you're prone to doing it again.  If that is true, it might be useful to know if R can be coerced into giving up that cached memory - there are definitely cases where one needs to e.g. load a very large network object, pull some specific info from it, and then get rid of it for subsequent analyses.  I'm speculating, though.  I looked quickly at `?Memory`, and it is vague on the matter.  The R Internals manual probably contains the truth, but I've not gone looking yet....

**Comment by CarterButts** [comment] 2022-07-27 20:00
FYI, one last (?) quick comment on this: I've done some poking around, and it looks like this behavior is indeed well-known and generic (i.e., not statnet-related).  If you google "R not releasing memory after gc" or similar, you'll find quite a lot of discussion on it going back many years.  I was not able to obtain a definitive answer, but the best explanation I saw was that R's ability to actually release memory back to the OS depends on how fragmented it is: large contiguous chunks may be able to be released, but lots of little ones may not.  The latter memory may still be re-used internally by the R process (so it's not "wasted" as such), but it will still count as part of R's footprint.  This would explain why e.g. deallocating a large vector leads to footprint reduction after `gc()`, while deallocating a large network object may not.  It's also possible that there is some deliberate caching going on, but in any event, this is a known behavior of the R garbage collector.  (This was my impression, but raising the question forced me to go look it up!)

**Comment by AdrienLeGuillou** [comment] 2022-07-27 20:35
Thanks for looking into this!
That explains a lot. R inner workings are a bit arcane.
