### ISSUE TITLE
installing statnet.common as dependency

### ISSUE THREAD

**Issue by keithegiles** [statnet/network#84] opened 2024-01-23 22:57 UTC
line 217 in matrix.utils.r in statnet.common throws an exception due to the new 'pipe' character.  I am using R 4.0.5 so it should recognize this but it doesn't.

**Comment by krivit** [comment] 2024-01-24 13:17
duplicate of https://github.com/statnet/statnet.common/issues/28

**Closed by krivit** 2024-01-24 13:17 UTC
